### PR TITLE
Cleanup package.json exports

### PR DESCRIPTION
**Pull request by arjunyel**
Copying the format from [`lago-javascript-client`](https://www.npmjs.com/package/lago-javascript-client?activeTab=code) which was [generated by dnt](https://arjunyel.com/blog/how-to-create-a-npm-package-in-2023/)

### CODE REVIEW

**Comment by arjunyel** [comment]
@lukewarlow sorry for all the PRs, I'm learning along side you :D When you're free could you cut a release? I believe thats all the changes that should be needed

**Comment by lukewarlow** [comment]
No worries! Thanks for the help. I'll cut a release now.

**Comment by lukewarlow** [comment]
That should be on npm as version 0.2.0

**Comment by arjunyel** [comment]
`removed 68 packages, changed 1 package`

Can confirm 0.2.0 fixes everything including VS Code tailwind intellisense :D

**Pull request merged**
